apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: web
          image: amir23156/devsecops-pipeline:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          securityContext:
            runAsUser: 1000        # numeric UID of appuser
            runAsGroup: 1000       # numeric GID of appuser
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
