name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: devsecops-pipeline   

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t myapp:latest -f app/Dockerfile .

      # Run Trivy vulnerability scan
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker Hub
      - name: Tag and push Docker image
        run: |
          set -euxo pipefail
          USER_LC=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          REPO="${USER_LC}/${IMAGE_NAME}"   # uses IMAGE_NAME from job env
          echo "Pushing image to Docker Hub: ${REPO}"

          docker tag myapp:latest ${REPO}:latest
          docker tag myapp:latest ${REPO}:${GITHUB_SHA::7}

          docker push ${REPO}:latest
          docker push ${REPO}:${GITHUB_SHA::7}

